### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by AskSkivdal** [benjarmstrong/qrcodetexture_godot_module#1]
I am getting this error.

i am using "scons -j 6" to compile

`
modules\qrcodetexture\qr_code_texture.cpp(2): fatal error C1083: Cannot open include file: 'qrcodegen.hpp': No such file or directory
scons: *** [modules\qrcodetexture\qr_code_texture.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
[Time elapsed: 00:01:02.785]
`

**Comment by AskSkivdal** [comment]
Fixed it. I had to add these two files:
https://raw.githubusercontent.com/nayuki/QR-Code-generator/master/cpp/qrcodegen.cpp
https://raw.githubusercontent.com/nayuki/QR-Code-generator/master/cpp/qrcodegen.hpp

**Comment by benjarmstrong** [comment]
This was because the ```qr_code_generator``` library was a git submodule. For it to work you would need to run:
```git submodule init && git submodule update```.

I've made an update so this is no longer needed - it should just work with a trivial download or ```git clone``` from now on.
